UNIFERS_KNOWLEDGE = {
    "company": {
        "name": "Unifers.ai",
        "description": "Unifers.ai is an all in one sales discovery and outreach automation platform that helps revenue teams discover verified contacts, enrich prospect data, verify information, and automate outreach workflows.",
        "positioning": "Help revenue teams find the right prospects, get reliable contact data, and move faster from discovery to outreach.",
        "public_workflow": "Find prospects -> Enrich data -> Verify info -> Launch outreach -> Convert",
        "sales_intelligence_workflow": "Find -> Understand -> Verify -> Score -> Recommend -> Act -> Learn",
    },
    "public_metrics": {
        "database": "350M+ shown on the public homepage; the workflow section also describes searching across 500M+ professionals.",
        "integrations": "30+ shown on the public homepage.",
        "coverage": "99% shown on the public homepage.",
        "teams": "10,000+ high growth revenue teams shown on the public homepage.",
        "important_note": "Treat public marketing metrics as claims displayed by Unifers and do not present them as independently audited figures.",
    },
    "products": [
        "Data Enrichment",
        "LinkedIn Extension",
        "LinkedIn Contact Finder",
        "APIs",
        "Email Deliverability",
        "Email Warmup",
    ],
    "product_notes": {
        "Data Enrichment": {
            "purpose": "Turns partial prospect or company records into richer profiles with information such as emails, phone numbers and social links.",
            "best_for": "Sales teams that already have lead records but need more complete information before qualification or outreach.",
        },
        "LinkedIn Extension": {
            "purpose": "Lets users work with verified contact information while browsing LinkedIn profiles and search results.",
            "best_for": "Prospectors who discover people on LinkedIn and want contact data without repeatedly switching tools.",
        },
        "LinkedIn Contact Finder": {
            "purpose": "Finds verified business emails and direct phone numbers from LinkedIn prospects.",
            "public_features": [
                "Chrome extension",
                "LinkedIn and Sales Navigator workflows",
                "Unlimited US email lookups",
                "Unlimited US phone lookups",
                "Search people and companies from the Unifers dashboard",
                "Bulk contact enrichment",
                "Export verified contacts",
                "Waterfall enrichment for contacts outside the US",
            ],
            "public_claims": "The public product page states 50K+ contacts enriched every day and 98% verified email accuracy.",
            "best_for": "Sales reps, founders and recruiters who prospect from LinkedIn, especially US prospecting teams.",
        },
        "APIs": {
            "purpose": "Programmatic access to contact intelligence and enrichment workflows.",
            "public_capabilities": [
                "LinkedIn profile enrichment",
                "Verified mobile numbers and personal emails",
                "Real time verification",
                "REST APIs",
                "Python, Node.js, Go and Java SDK support described publicly",
                "Webhooks",
                "OpenAPI and Swagger specifications",
                "Sandbox environment",
            ],
            "public_claims": "The API page describes 98% deliverability at the point of delivery and 99.9% uptime. Treat these as public product claims, not independent guarantees.",
            "best_for": "Engineering and revenue teams that want to put prospect enrichment directly into an application, CRM or internal workflow.",
        },
        "Email Deliverability": {
            "purpose": "Infrastructure focused on helping outbound email reach the inbox and protecting sender reputation.",
            "public_capabilities": [
                "Waterfall provider routing",
                "AI powered warmup",
                "Real time bounce protection",
                "Domain health monitoring",
                "Dynamic IP throttling",
                "Smart load balancing",
                "SPF, DKIM and DMARC management support",
            ],
            "public_claims": "The public page describes monitoring 150+ global blacklists and support for teams sending 100K+ emails monthly. Treat marketing percentages as public claims.",
        },
        "Email Warmup": {
            "purpose": "Automated sender reputation building for outbound email accounts and domains.",
            "public_capabilities": [
                "Automated warmup interactions",
                "Slow ramp technology",
                "Read emulation",
                "Live placement score",
                "Verified sender network",
                "One click Google Workspace or Microsoft 365 connection",
                "Target volume and provider settings",
            ],
            "public_claims": "The public page advertises 98% inbox placement and describes scaling from 5 to 5,000 domains. Treat these as public marketing claims.",
        },
    },
    "coming_soon": [
        "AI Outreach",
        "Unifers MCP",
        "Unifers Agent",
        "Multichannel Outreach",
        "Unified Inbox",
    ],
    "pricing": "Do not invent pricing. If asked for current pricing, use fresh web research or direct the user to the official Unifers site because pricing can change.",
    "data_honesty": "Never invent emails, phone numbers, company facts, funding, job titles, buying signals, integrations, pricing, relationships, private information or completed actions. If a field is not verified, say that it is not verified.",
    "prospecting_method": [
        "Define the ICP",
        "Find relevant companies",
        "Identify the right decision maker or persona",
        "Look for a credible buying or timing signal",
        "Verify company and contact information",
        "Score by ICP fit, relevance, timing and confidence",
        "Recommend the next action",
        "Personalize outreach",
        "Learn from campaign results",
    ],
    "official_sources": {
        "homepage": "https://unifers.ai/",
        "apis": "https://unifers.ai/apis",
        "linkedin_contact_finder": "https://unifers.ai/linkedin-contact-finder",
        "email_deliverability": "https://unifers.ai/email-deliverability",
        "email_warmup": "https://unifers.ai/email-warmup",
        "contact_sales": "https://unifers.ai/contact-sales",
    },
    "assistant_behavior": "Answer the user's exact question first. Use verified public Unifers knowledge. Distinguish facts from inference. For current or changing facts, prefer fresh web research. Never pretend an action was completed unless a connected system confirms it. When helping with prospecting, optimize for qualified conversations with the right prospects rather than lead volume.",
}
